/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthLogoutRouteImport } from './routes/_auth/logout'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppGroupIdRouteRouteImport } from './routes/app/$groupId/route'
import { Route as AppGroupIdMembersRouteImport } from './routes/app/$groupId/members'
import { Route as AppAdminRoomsIndexRouteImport } from './routes/app/admin/rooms/index'
import { Route as AppGroupIdSamplesIndexRouteImport } from './routes/app/$groupId/samples/index'
import { Route as AppGroupIdSamplesNewRouteImport } from './routes/app/$groupId/samples/new'
import { Route as AppGroupIdSamplesIdRouteImport } from './routes/app/$groupId/samples/$id'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/_auth/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGroupIdRouteRoute = AppGroupIdRouteRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupIdMembersRoute = AppGroupIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppGroupIdRouteRoute,
} as any)
const AppAdminRoomsIndexRoute = AppAdminRoomsIndexRouteImport.update({
  id: '/admin/rooms/',
  path: '/admin/rooms/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupIdSamplesIndexRoute = AppGroupIdSamplesIndexRouteImport.update({
  id: '/samples/',
  path: '/samples/',
  getParentRoute: () => AppGroupIdRouteRoute,
} as any)
const AppGroupIdSamplesNewRoute = AppGroupIdSamplesNewRouteImport.update({
  id: '/samples/new',
  path: '/samples/new',
  getParentRoute: () => AppGroupIdRouteRoute,
} as any)
const AppGroupIdSamplesIdRoute = AppGroupIdSamplesIdRouteImport.update({
  id: '/samples/$id',
  path: '/samples/$id',
  getParentRoute: () => AppGroupIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$groupId': typeof AppGroupIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/app/': typeof AppIndexRoute
  '/app/$groupId/members': typeof AppGroupIdMembersRoute
  '/app/$groupId/samples/$id': typeof AppGroupIdSamplesIdRoute
  '/app/$groupId/samples/new': typeof AppGroupIdSamplesNewRoute
  '/app/$groupId/samples/': typeof AppGroupIdSamplesIndexRoute
  '/app/admin/rooms/': typeof AppAdminRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$groupId': typeof AppGroupIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/app': typeof AppIndexRoute
  '/app/$groupId/members': typeof AppGroupIdMembersRoute
  '/app/$groupId/samples/$id': typeof AppGroupIdSamplesIdRoute
  '/app/$groupId/samples/new': typeof AppGroupIdSamplesNewRoute
  '/app/$groupId/samples': typeof AppGroupIdSamplesIndexRoute
  '/app/admin/rooms': typeof AppAdminRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$groupId': typeof AppGroupIdRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/app/': typeof AppIndexRoute
  '/app/$groupId/members': typeof AppGroupIdMembersRoute
  '/app/$groupId/samples/$id': typeof AppGroupIdSamplesIdRoute
  '/app/$groupId/samples/new': typeof AppGroupIdSamplesNewRoute
  '/app/$groupId/samples/': typeof AppGroupIdSamplesIndexRoute
  '/app/admin/rooms/': typeof AppAdminRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$groupId'
    | '/login'
    | '/logout'
    | '/app/'
    | '/app/$groupId/members'
    | '/app/$groupId/samples/$id'
    | '/app/$groupId/samples/new'
    | '/app/$groupId/samples/'
    | '/app/admin/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$groupId'
    | '/login'
    | '/logout'
    | '/app'
    | '/app/$groupId/members'
    | '/app/$groupId/samples/$id'
    | '/app/$groupId/samples/new'
    | '/app/$groupId/samples'
    | '/app/admin/rooms'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$groupId'
    | '/_auth/login'
    | '/_auth/logout'
    | '/app/'
    | '/app/$groupId/members'
    | '/app/$groupId/samples/$id'
    | '/app/$groupId/samples/new'
    | '/app/$groupId/samples/'
    | '/app/admin/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$groupId': {
      id: '/app/$groupId'
      path: '/$groupId'
      fullPath: '/app/$groupId'
      preLoaderRoute: typeof AppGroupIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$groupId/members': {
      id: '/app/$groupId/members'
      path: '/members'
      fullPath: '/app/$groupId/members'
      preLoaderRoute: typeof AppGroupIdMembersRouteImport
      parentRoute: typeof AppGroupIdRouteRoute
    }
    '/app/admin/rooms/': {
      id: '/app/admin/rooms/'
      path: '/admin/rooms'
      fullPath: '/app/admin/rooms/'
      preLoaderRoute: typeof AppAdminRoomsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$groupId/samples/': {
      id: '/app/$groupId/samples/'
      path: '/samples'
      fullPath: '/app/$groupId/samples/'
      preLoaderRoute: typeof AppGroupIdSamplesIndexRouteImport
      parentRoute: typeof AppGroupIdRouteRoute
    }
    '/app/$groupId/samples/new': {
      id: '/app/$groupId/samples/new'
      path: '/samples/new'
      fullPath: '/app/$groupId/samples/new'
      preLoaderRoute: typeof AppGroupIdSamplesNewRouteImport
      parentRoute: typeof AppGroupIdRouteRoute
    }
    '/app/$groupId/samples/$id': {
      id: '/app/$groupId/samples/$id'
      path: '/samples/$id'
      fullPath: '/app/$groupId/samples/$id'
      preLoaderRoute: typeof AppGroupIdSamplesIdRouteImport
      parentRoute: typeof AppGroupIdRouteRoute
    }
  }
}

interface AppGroupIdRouteRouteChildren {
  AppGroupIdMembersRoute: typeof AppGroupIdMembersRoute
  AppGroupIdSamplesIdRoute: typeof AppGroupIdSamplesIdRoute
  AppGroupIdSamplesNewRoute: typeof AppGroupIdSamplesNewRoute
  AppGroupIdSamplesIndexRoute: typeof AppGroupIdSamplesIndexRoute
}

const AppGroupIdRouteRouteChildren: AppGroupIdRouteRouteChildren = {
  AppGroupIdMembersRoute: AppGroupIdMembersRoute,
  AppGroupIdSamplesIdRoute: AppGroupIdSamplesIdRoute,
  AppGroupIdSamplesNewRoute: AppGroupIdSamplesNewRoute,
  AppGroupIdSamplesIndexRoute: AppGroupIdSamplesIndexRoute,
}

const AppGroupIdRouteRouteWithChildren = AppGroupIdRouteRoute._addFileChildren(
  AppGroupIdRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppGroupIdRouteRoute: typeof AppGroupIdRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAdminRoomsIndexRoute: typeof AppAdminRoomsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGroupIdRouteRoute: AppGroupIdRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAdminRoomsIndexRoute: AppAdminRoomsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
